<?php

namespace Venture\CustomerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository {
    public function getLatestCustomers($active = false, $limit = NULL) {
        $qb = $this->createQueryBuilder('c')
                    ->select('c')
                    ->addOrderBy('c.updated', 'DESC');
        
        if (true === $active)
            $qb->andWhere('c.isActive = :active')
               ->setParameter('active', $active);


        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
