<?php

namespace Venture\CommonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DataChangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataChangeLogRepository extends EntityRepository
{
    public function findLogByIntermediateId($id) {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.intermediates', 'i')
            ->where('i.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('c.loggedAt', 'DESC');

        return $qb->getQuery();
    }
}
