<?php

namespace Venture\CommonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaRepository extends EntityRepository
{
}
