<?php

namespace Venture\CommonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingDetailsRepository extends EntityRepository {
    
    
}
