<?php

namespace Venture\CompetitiveProductBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompetitiveProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitiveProductRepository extends EntityRepository
{

}
