<?php

namespace Venture\CompetitiveProductBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompetitiveProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitiveProductRepository extends EntityRepository
{
    public function getLatestProducts($active = false) {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->addOrderBy('p.updated', 'DESC');

        if (true === $active)
            $qb->andWhere('p.isActive = :active')
                ->setParameter('active', $active);


        return $qb->getQuery();
    }

}
