<?php

namespace Venture\FinishedProductBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinishedProductRepository extends EntityRepository {
    
    public function getLatestProducts($active = false, $limit = NULL) {
         $qb = $this->createQueryBuilder('p')
                    ->select('p')
                    ->addOrderBy('p.updated', 'DESC');
        
        if (true === $active)
            $qb->andWhere('p.isActive = :active')
               ->setParameter('active', $active);


        return $qb->getQuery();
    }
    
    public function getTotalPercentage($id, $active = true) {
         $query = $this->createQueryBuilder('p')
                ->select("SUM(f.amount) as total_amount")
                ->leftJoin("p.formulas", "f")
                ->where('p.id = :id')->setParameter('id', $id)
                ->andWhere('p.isActive = :active')->setParameter('active', $active)
                ->groupBy("f.finishedProduct")
                ->getQuery()
                ->getArrayResult();
        
        return array_shift($query);
    }
}
