<?php

namespace Venture\VendorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorRepository extends EntityRepository {
    
    public function getLatestVendors($active = false, $limit = NULL) {
        $qb = $this->createQueryBuilder('v')
                    ->select('v')
                    ->addOrderBy('v.updated', 'DESC');
        
        if (true === $active)
            $qb->andWhere('v.active = :active')
               ->setParameter('active', $active);


        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
    
    public function getCompanies($companyIds,$active = false) {
        $qb = $this->createQueryBuilder('v')
                    ->select('v')
                    ->where('v.id IN (:companyIds)')->setParameter('companyIds', $companyIds)
                    ->addOrderBy('v.id', 'DESC');
        
        if (true === $active)
            $qb->andWhere('v.active = :active')
               ->setParameter('active', $active);
        
        return $qb->getQuery()->getResult();
    }
}
