<?php

namespace Venture\RawMaterialsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RawMaterialsRepository extends EntityRepository {
    
    public function getLatestRawMaterials($active = false, $limit = NULL) {
         $qb = $this->createQueryBuilder('r')
                    ->select('r')
                    ->addOrderBy('r.updated', 'DESC');
        
        if (true === $active)
            $qb->andWhere('r.is_active = :active')
               ->setParameter('active', $active);


        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
