<?php

namespace Venture\AlternateRawMaterialBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlternateRawMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlternateRawMaterialRepository extends EntityRepository
{
    public function getLatestAlternateRawMaterials($active = false) {
        $qb = $this->createQueryBuilder('arm')
            ->select('arm')
            ->where('arm.isConvertedToRawMaterial = :isConvertedToRawMaterial')
            ->setParameter('isConvertedToRawMaterial', false)
            ->addOrderBy('arm.updated', 'DESC');

        if (true === $active)
            $qb->andWhere('arm.isActive = :active')
                ->setParameter('active', $active);

        return $qb->getQuery();
    }
}
