<?php

namespace Venture\AlternateRawMaterialBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlternateRawMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlternateRawMaterialRepository extends EntityRepository
{
    
}
