<?php

namespace Venture\PipeLineBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PipeLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipeLineRepository extends EntityRepository
{
}
