<?php

namespace Venture\PipeLineBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PipeLineYearSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipeLineYearSaleRepository extends EntityRepository
{
}
