<?php

namespace Settings\ConfigBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function getLatestLocations($limit = NULL) {
        $qb = $this->createQueryBuilder('l')
                    ->select('l')
                    ->addOrderBy('l.updated', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
