<?php

namespace Settings\ConfigBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PipelinetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipelinetypeRepository extends EntityRepository
{
}


