<?php

namespace Settings\ConfigBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SalesPricePointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesPricePointRepository extends EntityRepository
{
    public function getLatestPoints($limit = NULL) {
        $qb = $this->createQueryBuilder('spp')
                    ->select('spp')
                    ->addOrderBy('spp.updated', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                ->getResult();
    }
}
