<?php

namespace Settings\ConfigBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestProcedureRepository extends EntityRepository {
    
    public function getLatestProcedures($limit = NULL) {
        $qb = $this->createQueryBuilder('tp')
                    ->select('tp')
                    ->addOrderBy('tp.updated', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                ->getResult();
    }
}
